export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const VIDEO_LOADING = "VIDEO_LOADING";

export const GET_YOUTUBE_VIDEOS = "GET_YOUTUBE_VIDEOS";

export const GET_VIDEOS_USER = "GET_VIDEOS_USER";
export const ADD_VIDEO_USER_FAVOURITE = "ADD_VIDEO_USER_FAVOURITE";
export const GET_VIDEO_USER = "GET_VIDEO_USER";
export const DELETE_VIDEO_USER = "DELETE_VIDEO_USER";

export const ADD_VIDEO_USER_CATEGORY = "ADD_VIDEO_USER_CATEGORY";
export const GET_VIDEO_USER_CATEGORY = "GET_VIDEO_USER_CATEGORY";
export const GET_VIDEO_USER_CATEGORIES = "GET_VIDEO_USER_CATEGORIES";

export const GET_SETTINGS = "GET_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
