export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const VIDEO_LOADING = "VIDEO_LOADING";

export const GET_YOUTUBE_VIDEOS = "GET_YOUTUBE_VIDEOS";

export const GET_VIDEOS = "GET_VIDEOS";
export const ADD_VIDEO_FAVOURITE = "ADD_VIDEO_FAVOURITE";
export const DELETE_VIDEO = "DELETE_VIDEO";

export const ADD_VIDEO_USER_CATEGORY = "ADD_VIDEO_USER_CATEGORY";
export const GET_VIDEO_USER_CATEGORY = "GET_VIDEO_USER_CATEGORY";
export const GET_VIDEO_USER_CATEGORIES = "GET_VIDEO_USER_CATEGORIES";

export const GET_SETTINGS = "GET_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
